from django.db import models

# Create your models here.
class Company(models.Model):
    #consortium = models.CharField(max_length=10)
    company_id = models.AutoField(primary_key=True)
    short_name = models.CharField(max_length=15)
    company_name1 = models.CharField(max_length=30)
    company_name2 = models.CharField(max_length=30, blank=True, null=True)
    street = models.TextField()
    country_code = models.CharField(max_length=3)
    zip_code = models.CharField(max_length=6, blank=True, null=True)
    town = models.CharField(max_length=20)
    country = models.CharField(max_length=30, blank=True, null=True)
    contact_person = models.CharField(max_length=30)
    email = models.CharField(max_length=40)
    tel_no = models.CharField(max_length=15)
    fax_no = models.CharField(max_length=15)
    company_logo = models.IntegerField()
    company_url = models.CharField(max_length=40, blank=True, null=True)
    createdby = models.CharField(max_length=50,default=None)
    createddate = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    modifiedby = models.CharField(max_length=50,default=None)
    modifieddate = models.DateTimeField(auto_now=True,null=True,blank=True)
    tax_no1 = models.CharField(max_length=40)
    tax_no2 = models.CharField(max_length=40)


class Consortium(models.Model):
    consortium_id = models.AutoField(primary_key=True)
    short_name = models.CharField(unique=True, max_length=15)
    consortium_name1 = models.CharField(max_length=30, blank=True, null=True)
    consortium_name2 = models.CharField(max_length=30, blank=True, null=True)
    street = models.CharField(max_length=30, blank=True, null=True)
    country_code = models.CharField(max_length=3, blank=True, null=True)
    zip_code = models.CharField(max_length=5, blank=True, null=True)
    town = models.CharField(max_length=20, blank=True, null=True)
    country = models.CharField(max_length=30, blank=True, null=True)
    contact_person = models.CharField(max_length=30, blank=True, null=True)
    email = models.CharField(max_length=40, blank=True, null=True)
    tel_no = models.CharField(max_length=15, blank=True, null=True)
    fax_no = models.CharField(max_length=15, blank=True, null=True)
    energy_type = models.SmallIntegerField(blank=True, null=True)
    usable = models.CharField(max_length=1, blank=True, null=True)
    createdby = models.CharField(max_length=50, blank=True, null=True)
    createddate = models.DateTimeField(blank=True, null=True)
    modifiedby = models.CharField(max_length=50, blank=True, null=True)
    modifieddate = models.DateTimeField(blank=True, null=True)
    consortium_logo = models.IntegerField(blank=True, null=True)
    tax_no1 = models.CharField(max_length=40)
    tax_no2 = models.CharField(max_length=40)

class Location(models.Model):
    company = models.ForeignKey(Company, models.DO_NOTHING, blank=True, null=True)
    location_id = models.AutoField(primary_key=True)
    short_name = models.CharField(max_length=15, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    street = models.TextField(blank=True, null=True)
    country_code = models.CharField(max_length=3, blank=True, null=True)
    zip_code = models.CharField(max_length=6, blank=True, null=True)
    town = models.CharField(max_length=20, blank=True, null=True)
    country = models.CharField(max_length=30, blank=True, null=True)
    contact_person = models.CharField(max_length=30, blank=True, null=True)
    email = models.CharField(max_length=40, blank=True, null=True)
    tel_no = models.CharField(max_length=15, blank=True, null=True)
    fax_no = models.CharField(max_length=15, blank=True, null=True)
    #penalty_price = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    #penalty_limit = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    #provider_id = models.IntegerField(blank=True, null=True)
    #energy_id = models.IntegerField(blank=True, null=True)
    #free_client = models.CharField(max_length=1, blank=True, null=True)
    #billing_id = models.PositiveIntegerField(blank=True, null=True)
    #contact_id = models.IntegerField(blank=True, null=True)
    #remarks = models.CharField(max_length=120, blank=True, null=True)
    #invoice_marker = models.CharField(max_length=10, blank=True, null=True)
    #residential_provider_id = models.IntegerField(blank=True, null=True)
    #residential_billing_id = models.IntegerField(blank=True, null=True)
    #location_type = models.CharField(max_length=25, blank=True, null=True)
    #state = models.CharField(max_length=1, blank=True, null=True)
    #usable = models.CharField(max_length=1)
    #createdby = models.CharField(max_length=50, blank=True, null=True)
    #createddate = models.DateTimeField(blank=True, null=True)
    #modifiedby = models.CharField(max_length=50, blank=True, null=True)
    #modifieddate = models.DateTimeField(blank=True, null=True)
    location_logo = models.IntegerField(blank=True, null=True)
    #contentright = models.CharField(max_length=1, blank=True, null=True)

class Area(models.Model):
    company = models.ForeignKey(Company, models.DO_NOTHING, blank=True, null=True)
    location = models.CharField(max_length=50)
    area = models.CharField(max_length=50)
    area_logo = models.CharField(max_length=100)
