# Generated by Django 3.2.2 on 2021-05-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=15)),
                ('company_name1', models.CharField(max_length=30)),
                ('company_name2', models.CharField(blank=True, max_length=30, null=True)),
                ('street', models.TextField()),
                ('country_code', models.CharField(max_length=3)),
                ('zip_code', models.CharField(blank=True, max_length=6, null=True)),
                ('town', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_person', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('tel_no', models.CharField(max_length=15)),
                ('fax_no', models.CharField(max_length=15)),
                ('company_logo', models.IntegerField()),
                ('company_url', models.CharField(blank=True, max_length=40, null=True)),
                ('createdby', models.CharField(default=None, max_length=50)),
                ('createddate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modifiedby', models.CharField(default=None, max_length=50)),
                ('modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('tax_no1', models.CharField(max_length=40)),
                ('tax_no2', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Consortium',
            fields=[
                ('consortium_id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=15, unique=True)),
                ('consortium_name1', models.CharField(blank=True, max_length=30, null=True)),
                ('consortium_name2', models.CharField(blank=True, max_length=30, null=True)),
                ('street', models.CharField(blank=True, max_length=30, null=True)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True)),
                ('town', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('tel_no', models.CharField(blank=True, max_length=15, null=True)),
                ('fax_no', models.CharField(blank=True, max_length=15, null=True)),
                ('energy_type', models.SmallIntegerField(blank=True, null=True)),
                ('usable', models.CharField(blank=True, max_length=1, null=True)),
                ('createdby', models.CharField(blank=True, max_length=50, null=True)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('modifiedby', models.CharField(blank=True, max_length=50, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
                ('consortium_logo', models.IntegerField(blank=True, null=True)),
                ('tax_no1', models.CharField(max_length=40)),
                ('tax_no2', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=6, null=True)),
                ('town', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('tel_no', models.CharField(blank=True, max_length=15, null=True)),
                ('fax_no', models.CharField(blank=True, max_length=15, null=True)),
                ('location_logo', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='site_ems.company')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('area_logo', models.CharField(max_length=100)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='site_ems.company')),
            ],
        ),
    ]
