# Generated by Django 3.1.6 on 2021-05-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
