# Generated by Django 3.2.2 on 2021-05-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_ems', '0002_alter_area_company'),
        ('site_ems', '0002_auto_20210519_0929'),
    ]

    operations = [
    ]
