# Generated by Django 3.2.2 on 2021-05-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_ems', '0004_alter_area_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_ems.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_ems.company'),
        ),
    ]
