# Generated by Django 3.2.2 on 2021-05-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ems', '0005_auto_20210521_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='createdby',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='area',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='modifiedby',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='area',
            name='modifieddate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
